config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :destroy, :update, :show, :edit]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root 'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :description, presence: true, length: { minimum: 5 }

  belongs_to :user

  has_many :likes, dependent: :destroy

  extend FriendlyId
  friendly_id :generated_hash, use: :slugged

  def generated_hash
    require 'securerandom'
    @generated_hash ||= persisted? ? Friendly_id : SecureRandom.hex(4)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = Recipe.includes([:user], user: { avatar_photo_attachment: :blob }).all.order(created_at: :desc)
    @users = User.all.order(created_at: :desc).with_attached_avatar_photo
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to root_path
    else
      redirect_to request.referrer, alert: 'Recipe was not created'
    end
  end

  def destroy
    authorize @recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_recipe
    @recipe = Recipe.friendly.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:description, :avatar, :users)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@recipe) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :description

  .form-actions
    = f.button :submit,  class: 'btn btn-success'

app/views/recipes/_main.html.haml
.row.bg-white.mr-5.mt-5
  = render 'recipes/recipe_from_index'
%br

- @recipes.each do |recipe|
  .row.bg-white.mr-5.py-4
    .col-1.ml-2
      = image_tag avatar_for(recipe.user), height: "50px", width: "50px", class: "rounded-circle"
    .col-8.ml-3
      .row
        %h6
          = link_to recipe.user.fullname, user_path(recipe.user)
          %small
            = link_to "@" + recipe.user.username, user_path(recipe.user)
      .row
        %p= recipe.description
    .col-2
      .row
        = time_ago_in_words(recipe.created_at)
      .row
        = authorized_edit?(recipe)

app/views/recipes/_post_from_index.html.haml
.container.bg-white.mt-4.mr-5.mb-4
  = form_for(Recipe.new, :url => { :action => "create" })  do |form|
    %p.pl-4.mb-1.ml-3.pt-3
      Say something
    .row.justify-content-center
      .col-11.pt-0
        = form.text_field :description, class: 'form-control', placeholder: 'Add new Recipe'
    .row.justify-content-end
      .col-3.pt-2.mr-4.mb-4
        .form-actions
          = form.submit 'Post New Recipe', method: :post, class: 'btn btn-twitter'

app/views/recipes/_recipe_from_index.html.haml
.container
  = form_for(Recipe.new, :url => { :action => "create", :controller=>"recipes", :id=> current_user.id })  do |form|
    %p.pl-4.mb-1.ml-3.pt-3
      Say something
    .row.justify-content-center
      .col-11.pt-0
        = form.text_field :description, class: 'form-control', placeholder: 'Add new Recipe'
    .row.justify-content-end
      .col-3.pt-3.mr-4.mb-3
        .form-actions
          = form.submit 'Post New Recipe', method: :post, class: 'btn btn-primary'

app/views/recipes/_rightbar.html.haml
.row.py-3
  .col-3
    = image_tag avatar_for(user), height: "60x", width: "60px", class: "rounded-circle"
  .col-6
    .row
      %h5.pl-3
        = link_to user.username, user_path(user), class: 'profile-link'
    .row
      %h6.pl-3
        = user.fullname
  .col-3
    = relationship_button(user, current_user)

app/views/recipes/edit.html.haml
%h1 Editing recipe

= render 'form'

= link_to 'Show', @recipe
\|
= link_to 'Back', recipes_path

app/views/recipes/index.html.haml
.container-fluid.d-flex.pt-2
  .col-9.pt-2
    .row 
      .card-columns.border-bottom-0
        .rectangle-4
        .rectangle-41
        .rectangle-6
        %h5 Recipes
    = render 'recipes/main'
  .col-3.pt-2
    .row
      %nav
        %h5.pl-1
          Who to Follow
        .sidebar-header.pl-1
          - @users.each do |user|
            = who_to_follow(user)

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'

= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @recipe.description

= link_to 'Edit', edit_recipe_path(@recipe)
\|
= link_to 'Back', recipes_path