config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  resources :users, only: [:new, :create, :destroy, :update, :show, :edit]
  resources :relationships, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  root 'recipes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%footer.footer.purple-background.text-light
  .container
    %br
    .row
      .col-md-4
        = link_to 'Home', root_path
        .row
        About us
      .col-md-3
        Privacy policy
        .row
        Terms and conditions
        .row
        Careers
        .row
        Help and Support
        .row
        Blog
        .row
        %br
      .col-md-3
        Copyright
        © 
        = Time.now.year
        .row
        %br
        .row
        .fa.fa-envelope
        = mail_to 'g.axl.aquila@gmail.com'
      .col-md-2
        %b.pl-5
          BALANCE
          .fas.fa-egg.fa-lg.pl-2
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-twitter.pb-3.pt-3
  %a.navbar-brand{:href => root_path}
    %h5.pl-3
      BALANCE
      .fas.fa-egg.fa-lg.pl-2
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto.pl-2
        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
        -#   = link_to root_path, class: 'nav-link' do
        -#     .fab.fa-twitter
        -#     Home
        -# %li.nav-item{class: "#{'active font-weight-bold' if current_page?(recipes_path)}"}
        -#   = link_to recipes_path, class: 'nav-link' do
        -#     .fa.fa-book.fa-lg
        -#     Recipes
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_recipe_path)}"}
          = link_to new_recipe_path, class: 'nav-link' do
            .fas.fa-pen.fa-lg
      %ul.navbar-nav.mr-right.pl-2
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_recipe_path)}"}
          = link_to new_recipe_path, class: 'nav-link' do
            .fas.fa-envelope.fa-lg
      %ul.navbar-nav.mr-right.pl-2
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_recipe_path)}"}
          = link_to new_recipe_path, class: 'nav-link' do
            .fas.fa-search.fa-lg
        %li.nav-item.dropdown.pr-3.pl-2
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            .fa.fa-cog.fa-lg
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt.fa-lg
              %b Sign out

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'gray' : 'danger'} align-self-bottom", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_sidebar.html.haml
- if signed_in? 
  %nav#sidebar
    .sidebar-header
      %h6
        = image_tag avatar_for(current_user), height: "64px", width: "64px", class: "rounded-circle" 
        %b.pl-2
          = link_to current_user.fullname, user_path(current_user)
    .row     
      .pl-5.pr-3.py-2.border-r-2
        %h5.px-4.ml-1
          %strong
            = current_user.followers.count
        Followers
      .pl-3.py-2.border-r-2
        %h5.pl-4.ml-1
          %strong
            = current_user.followed_users.count 
        Following
    %p.align-self-bottom
      = render 'layouts/messages'       

    .sidebar-header
    %ul.list-unstyled.components
      %li.active
        %a{:href => root_path}
          .fa.fa-home 
          %b Home
      %li
        = link_to edit_user_registration_path, class: "dropdown-item" do
          .fa.fa-cog.fa-lg
          %b Edit Profile

app/views/layouts/_sidebar_before_signed.html.haml
%nav#sidebar
  .sidebar-header
    %ul.navbar-nav.pt-5
      %li.nav-item.pt-5
        %h4
          - if devise_mapping.registerable? && controller_name != 'registrations'
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link bg-primary text-light'
            = link_to 'Log In', new_user_session_path, class: 'nav-link bg-light text-primary'
          - if controller_name != 'sessions'
            = link_to 'Sign Up', new_user_registration_path, class: 'nav-link bg-light text-primary'
            = link_to 'Log In', new_user_session_path, class: 'nav-link bg-primary text-light'
      %li.nav-item.pt-5
        %i.fas.fa-egg.fa-10x.pl-5
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Balance
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "https://i.postimg.cc/9MpGPrZc/balancepreview.png", :property => "og:image"}/
    
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    
  %body
    .container-fluid
      .row.h-100
        .col-2.grid-left.p-0
          = signed
        .col-10
          .row
            .col-12.p-0
              = render 'layouts/header'
          .row
            .col-12.border.border-left-0.border-bottom-0.p-0.bg-twittergrey
              .container
                = yield
    = render 'layouts/footer'